export const enum RouteNames {
  HOME = 'home',
  LOGIN = 'login',
  REGISTER = 'register',
  ADOPT = 'adopt',
  ADOPT_DETAIL = 'adopt-detail',
  ADOPTION_FORM = 'adoption-form',
  DISCOVER = 'discover',
  DISCOVER_LIKES = 'discover-likes',
  BLOG = 'blog',
  BLOG_DETAIL = 'blog-detail',
  DASHBOARD = 'dashboard',
  DASHBOARD_USERS = 'dashboard-users',
  DASHBOARD_SETTINGS = 'dashboard-settings',
  DASHBOARD_ANALYTICS = 'dashboard-analytics',
  DASHBOARD_CATS = 'dashboard-cats',
  DASHBOARD_ABSENCES = 'dashboard-absences',
  DASHBOARD_BLOG = 'dashboard-blog',
  DASHBOARD_TARIFICATIONS = 'dashboard-tarifications',
  DASHBOARD_ADOPTION_REQUESTS = 'dashboard-adoption-requests',
}
