/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminAppNavBar: typeof import('./src/components/AdminAppNavBar.vue')['default']
    AppNavBar: typeof import('./src/components/AppNavBar.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    CatFormPanel: typeof import('./src/components/Forms/CatFormPanel.vue')['default']
    CatGalleryModal: typeof import('./src/components/Modals/CatGalleryModal.vue')['default']
    CatSheetGeneralPanel: typeof import('./src/components/Forms/CatSheetGeneralPanel.vue')['default']
    CatSheetImagesPanel: typeof import('./src/components/Forms/CatSheetImagesPanel.vue')['default']
    CatSheetModal: typeof import('./src/components/Modals/CatSheetModal.vue')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    DatePickerWithLabel: typeof import('./src/components/Forms/elements/DatePickerWithLabel.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EditUserModal: typeof import('./src/components/Modals/EditUserModal.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    Galleria: typeof import('primevue/galleria')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputNumberWithLabel: typeof import('./src/components/Forms/elements/InputNumberWithLabel.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    InputTextWithLabel: typeof import('./src/components/Forms/elements/InputTextWithLabel.vue')['default']
    LoginFormComponent: typeof import('./src/components/Forms/Auth/LoginFormComponent.vue')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    MultiSelectWithLabel: typeof import('./src/components/Forms/elements/MultiSelectWithLabel.vue')['default']
    Popover: typeof import('primevue/popover')['default']
    Rating: typeof import('primevue/rating')['default']
    RegisterFormComponenet: typeof import('./src/components/Forms/Auth/RegisterFormComponenet.vue')['default']
    RegisterFormComponent: typeof import('./src/components/Forms/Auth/RegisterFormComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInputTextComponent: typeof import('./src/components/Inputs/SearchInputTextComponent.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectWithLabel: typeof import('./src/components/Forms/elements/SelectWithLabel.vue')['default']
    Step: typeof import('primevue/step')['default']
    StepList: typeof import('primevue/steplist')['default']
    StepPanel: typeof import('primevue/steppanel')['default']
    StepPanels: typeof import('primevue/steppanels')['default']
    Stepper: typeof import('primevue/stepper')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    ToggleSwitchWithLabel: typeof import('./src/components/Forms/elements/ToggleSwitchWithLabel.vue')['default']
    UserModal: typeof import('./src/components/Modals/UserModal.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
