/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminAppNavBar: typeof import('./src/components/AdminAppNavBar.vue')['default']
    AppNavBar: typeof import('./src/components/AppNavBar.vue')['default']
    Button: typeof import('primevue/button')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginFormComponent: typeof import('./src/components/Forms/Auth/LoginFormComponent.vue')['default']
    Message: typeof import('primevue/message')['default']
    RegisterFormComponenet: typeof import('./src/components/Forms/Auth/RegisterFormComponenet.vue')['default']
    RegisterFormComponent: typeof import('./src/components/Forms/Auth/RegisterFormComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInputTextComponent: typeof import('./src/components/Inputs/SearchInputTextComponent.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
